# +---------------------------------------------------------------------
# | CREATE SERVICE CONNECT TO EXTERNAL MYSQL FOR DEVELOPMENT ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +---------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ns-development
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/instance: employees
    app.kubernetes.io/version: "1.0.5"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: api-employee
    app.kubernetes.io/managed-by: github.com
    app: api-employees
    owner: taa
    env: dev
    type: configuration
spec:
  ports:
    - name: "mysql"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
      nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: ns-development
  labels:
    app: api-employees
    owner: taa
    env: dev
    type: configuration
subsets:
  - addresses:
      - ip: 192.168.59.107
    ports:
      - port: 33060
        name: "mysql"