apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-development
  namespace: ns-development
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/instance: employees
    app.kubernetes.io/version: "1.0.5"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: api-employee
    app.kubernetes.io/managed-by: github.com
    app: api-employees
    owner: taa
    env: dev
    type: configuration
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    server: 192.168.59.111
    path: "/mnt/nfs_server"