apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sc-application-credential-development
  namespace: ns-development
spec:
  encryptedData:
    KEY_DB_EMPLOYEES_PASSWORD: AgC5JRPaZaxWxfoY/YWYOCVJCpNhK+DzCrLPuDEL+IsS/f5kgjgLCDSfiCkhcjjkNoprd3tY3BnYqlUG4sNQ+mblfM79WMIvSYbVZd2vEd5fwMrGGN4X8r9L8U3igzPXyfOvD9uxuHqcsvZGvwhxXILQZ23NWOUYyaj1jio+/AsWd2oDVSD1+F1iJLt9z64gVimFyeWDRs3WvP9WPomTkTqauoXt8jCvsqvnSoFvI1vOvU7y0nR0HthFkfCMdmSrwAOQIxDdQ8NRm4zUQckMwECQy+t5mRACjZyCQSP1QFTXi8Yxqce6yPwHtWEza7x8Vry6i/hmLUwEQqgGSpVEqJWNP2NiUGsy4VFGOv4UjShaMnAy8SbQwqGIJgvGY+gmc0Eud0833c47+GSEPo1qXbdEqqwNZRS9xi7slxXpG+P1rx+TCdqgcU/kiu6jlcQNWyCJiEwhOTCodE/i7w8VM5RmMhHPoWpk7vrl/ysMR1laRWjl4Tam+y+F5YLXtJWuQHLW63Ju6CcbSU5K025DPhhn4yhcyAjTet8f4IGx9KDdB2lHJOJxxSpfcn8hdQOdmOvTI0w2Haio2mzfe5bie11bmeRdnGr1A/JZA5EffMDRoq7M9Q8G84WU3CdC/6egKpdSGaFA4lrtappQPeuPMpvIiwoSaq9USOkiaeKJfFiqWW2JAOy2tabczLxRYGNfHu1b83gWalxUIZ23k+8kZMJp0zwzT58WVxc9UpNUEl5FUtwhVZo=
    KEY_DB_EMPLOYEES_USERNAME: AgBkj8NkO01EgHd8I50BddM3/1IrghNo3nd/BcZ70TgB7/85Xz+k225fFjxGYqkzRmPep//b/1CulDv8X7613VZ4uMgXXtHg33bABhW19FA1SFQJMzesG1m+uS3ThqftljCEL5laORrTE4VQvbSMyZkihr5jnFJ3+cdNk8P8Cq84aU5j8yhy9hi21iuD4QMfK4s9r5/Eu9qlEZIlL2P7F/gvgJc1Hh0kJV8gxmnI59IkvwVtB1yo8jK/lw8kUUjRph8BTIEGIdIH/Qz+ZHY4M9xoX83zmLIqbBb6GAusVa+IeoNUg7bIp5fO9qZPRAByYTwUlqq/hJOIDIWMk10oORv+R7fvVI6ejxr1J7oTXEq+fogp/TldkwLKn110r2hC9JBbvWzJac44FdSAD8RDBx4BTIUZ+axzpRh6H4AhlZtzeEH7NcRaT6u4CjrOU5Q9fcYygGstCrfoPJQ4jk1yAkMvKnxJlHDTuEvzOkAwNoDaZM1fg416HZ1g5r6TQNAjhEX9p7GBMF/uJFKIxV0Lakrm0jtUD9KlI4Fm3feAx9rAr52p59YCuLdJ9i+av5IFpc/GiHHMszu0vThUE7xEShp+j9M0o4GUuC+ANCDRo7RDFVr+6zo+Rjn1qWS9kJECX32iaqBaNCVYVYTYAur14B4fS0jZOc2eL9HysETige7VeV+83BxmeQhtcdCG14kYgXpDlMvJcyau8J8=
    KEY_KEYCLOAK_RESOURCE_SECRET: AgCh4A4oD/R7Hh2DFEA9u+VXCcQndSkvwkJHnupNEdVZDzoSiF9IF3/Xe8xkzmfQDmY+0jKHHSn+nG28JrHdXjFaiZX8Kf87bSoIRAkvk/PKvTrQJsIaW+sgV8CCtvhdn3XHSty/gA0tKfILVkakQxUKzBAdHSeoYImzEjzxvYklU57DgztnNw3ark/ryD1wDLzroCJNrXwzx4a9y3ClYoDO7iZb5EhR79Wx6Pmz4GyCSxfaQcgSQOF4hseskcK9UywEjhA8k1wXaHQ3GKC1xs3YT1r5NVoWYJ3dwOyrIl1h9CYHiKPZZ4mlbKKUDmDEFGW2NNbYndcki2OP+7FHHggtG+4+lliT67ZeyMSOg8Gq8WmugBPPkQP6ZUrcVVfh2D7IM3vU/eOz8U7d4tzohiXQ0CXs9ewTBi5wxVBWo6sHP+6rgJLXa9Wzv2hnH394XpOeKkbXgHU8gee3l5yqE7+LI4ync+76eG27DNnQZWe/bm2iLU63sSIqTIvUY/BANQrX/IxE0KK2/Ufs2qUdn9+wJNGLgh/Q6rbV9LJAzbwC1TwUe6OTofyBYlIFUhI25LK3CKTMsDrQaRLT8WEAoqFoaOrzxkb0aIQtxIafIYj5stlvmF9RFRie7AQu4yRP9nI1E5z8VnaxS3cwLAZkRxhmIUfZ/RCx4yNA0DJT11XAE5Q6qEEtBOy0q+uq3gRXpNnh8s5ApVAzcleJkQk7cz4HYPYEcJ+6/6NHvbqeVXAW/g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: api-employees
        app.kubernetes.io/component: microservice
        app.kubernetes.io/instance: employees
        app.kubernetes.io/managed-by: github.com
        app.kubernetes.io/name: employees
        app.kubernetes.io/part-of: api-employee
        app.kubernetes.io/version: 1.0.5
        env: dev
        owner: taa
        type: database
      name: sc-application-credential-development
      namespace: ns-development
    type: Opaque

