# +--------------------------------------------------
# | CREATE DEPLOYMENT FOR DEVELOPMENT ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 10-01-2022
# +--------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlt-api-employees
  namespace: ns-development
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/instance: employees
    app.kubernetes.io/version: "1.0.5"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: api-employee
    app.kubernetes.io/managed-by: github.com
    owner: taa
    env: dev
    type: application
    app: api-employees
spec:
  selector:
    matchLabels:
      owner: taa
      env: dev
      type: application
      app: api-employees
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        owner: taa
        env: dev
        type: application
        app: api-employees
    spec:
      volumes:
        - name: vlm-dev-nfs-storage
          persistentVolumeClaim:
            claimName: pvc-development
      containers:
        - name: employee-services
          image: {{IMAGE_NAME}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: monitor
              containerPort: 9090
          env:
            - name: APP_FILESYSTEM
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_APP_FILESYSTEM
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_APP_ENVIRONMENT
            - name: DB_EMPLOYEES_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_DB_EMPLOYEES_CONNECTION
            - name: DB_EMPLOYEES_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_DB_EMPLOYEES_NAME            
            - name: KEYCLOAK_URL_BASE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_KEYCLOAK_URL_BASE_CONNECTION
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_KEYCLOAK_REALM
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_KEYCLOAK_RESOURCE
            - name: DB_EMPLOYEES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sc-application-credential-development
                  key: KEY_DB_EMPLOYEES_USERNAME
            - name: DB_EMPLOYEES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-application-credential-development
                  key: KEY_DB_EMPLOYEES_PASSWORD
            - name: KEYCLOAK_RESOURCE_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-application-credential-development
                  key: KEY_KEYCLOAK_RESOURCE_SECRET                  
          volumeMounts:
            - name: vlm-dev-nfs-storage
              mountPath: "/employee/dev/data"
          resources:
            requests:
              memory: "200Mi"
              cpu: "300m"
            limits:
              memory: "300Mi"
              cpu: "400m"
          startupProbe:
            httpGet:
              path: /ping
              port: 8080
            failureThreshold: 30
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 65
            timeoutSeconds: 65
            httpGet:
              path: /monitor/actuator/health/readiness
              port: 9090
          livenessProbe:
            initialDelaySeconds: 65
            periodSeconds: 3
            httpGet:
              path: /monitor/actuator/health/liveness
              port: 9090
