# +--------------------------------------------------
# | CREATE SERVICE FOR DEVELOPMENT ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 10-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: svc-employee-services-development
  namespace: ns-development
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/instance: employees
    app.kubernetes.io/version: "1.0.5"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: api-employee
    app.kubernetes.io/managed-by: github.com
    owner: taa
    env: dev
    type: application
    app: api-employees
spec:
  selector:
    owner: taa
    env: dev
    type: application
    app: api-employees
  type: NodePort
  ports:
    - name: http-app
      port: 8080
      targetPort: 8080
    - name: http-mng
      port: 9090
      targetPort: 9090