# +--------------------------------------------------
# | CREATE DEPLOYMENT FOR PRODUCTION ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 10-01-2022
# +--------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlt-api-employees
  namespace: ns-production
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/instance: employees
    app.kubernetes.io/version: "1.0.5"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: api-employee
    app.kubernetes.io/managed-by: github.com
    owner: taa
    env: prd
    type: application
    app: api-employees
spec:
  selector:
    matchLabels:
      owner: taa
      env: prd
      type: application
      app: api-employees
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  template:
    metadata:
      labels:
        owner: taa
        env: prd
        type: application
        app: api-employees
    spec:
      volumes:
        - name: vlm-prd-nfs-storage
          persistentVolumeClaim:
            claimName: pvc-production
      containers:
        - name: employee-services
          image: wortiz1027/employee-services:v1.0.5-20220117180152
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: monitor
              containerPort: 9090
          env:
            - name: APP_FILESYSTEM
              valueFrom:
                configMapKeyRef:
                  name: cm-application-production
                  key: KEY_APP_FILESYSTEM
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: cm-application-production
                  key: KEY_APP_ENVIRONMENT
            - name: DB_EMPLOYEES_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: cm-application-production
                  key: KEY_DB_EMPLOYEES_CONNECTION
            - name: DB_EMPLOYEES_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-application-production
                  key: KEY_DB_EMPLOYEES_NAME
            - name: DB_EMPLOYEES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sc-db-credential-production
                  key: KEY_DB_EMPLOYEES_USERNAME
            - name: DB_EMPLOYEES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-db-credential-production
                  key: KEY_DB_EMPLOYEES_PASSWORD
          volumeMounts:
            - name: vlm-prd-nfs-storage
              mountPath: "/employee/prd/data"
          resources:
            requests:
              memory: "250Mi"
              cpu: "350m"
            limits:
              memory: "350Mi"
              cpu: "450m"
          startupProbe:
            httpGet:
              path: /ping
              port: 8080
            failureThreshold: 30
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 65
            timeoutSeconds: 65
            httpGet:
              path: /monitor/actuator/health/readiness
              port: 9090
          livenessProbe:
            initialDelaySeconds: 65
            periodSeconds: 3
            httpGet:
              path: /monitor/actuator/health/liveness
              port: 9090